### ISSUE TITLE
index js animation

### ISSUE THREAD

**Issue by 0pia** [mtlhdnrd/harenae_castrum#8]
the arrow needs to be clicked on an extra time before it allows the user to go down again. can you look at that please? :c

**Comment by mtlhdnrd** [comment]
ChatGPT hallucinated two incredibly incorrect scroll state checks, store it separately instead, or just use the arrow's display style and act on those

**Comment by mtlhdnrd** [comment]
also, three states somehow??? sure, if there's a separate state during the scroll animation, but wtf??
